config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  root 'pages#home'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  get 'user/:id', to: 'users#show', as: 'user'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Filters out specific user
  scope :all_except, -> (user) { where.not(id: user)}
  # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # The exclamation mark is a convention used by Devise to indicate that this method may perform a forceful action
  before_action :authenticate_user!
  def index
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Turbochat</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS Only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <!-- Renders == Display
      this renders the "partials", which contains the templates for the application
     -->
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Turbochat</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to("Start Chatting", rooms_path) %>
<% if user_signed_in? %>
  <%= button_to('Log Out', destroy_user_session_path, method: :delete) %>
<% else %>
  <%= link_to('Sign Up', new_user_registration_path) %>
  <%= link_to('Log In', new_user_session_path) %>
<% end %>

app/views/rooms/_room.html.erb
<div>
    <%= link_to room.name, room %>
</div>

app/views/rooms/index.html.erb
<div class="container">
    <h5> <%= current_user.email%> </h5>
    <h4> Users </h4>
    <%= render partial: "users/user", collection: @users %>
    <h4> Rooms </h4>
    <%= render partial: 'rooms/room', collection: @rooms %>
</div>

app/views/users/_user.html.erb
<div class="list-group">
    <div class="list-group-item list-group-item-action">
        <%= link_to user.email, user %>
    </div>
</div>